/// <reference types="node" />
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { BLEND_HALF_LIFE_MIN, HEADER_SIZE, WEEK_UNKNOWN, blend, parseWeek, probabilityAt, weekBucket } from "../src/week";

// Resolved through `fileURLToPath` rather than `new URL("...", import.meta.url)`:
// Vite rewrites that literal pattern at transform time into an asset URL, which
// here would resolve to `http://localhost/...` and never reach the disk. Same
// pattern `tests/icons.test.ts` uses for its own generated-file fixtures.
const WEB = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * `(ts, bucket)` pairs computed by the *real* `forecast.week_bucket`
 * (`scripts/build-seam-fixture.py` -> `tests/test_seam_fixture.py`), never
 * typed by hand here. See that script's module docstring and the Stage A
 * task-5 brief for why a hand-written table would only restate one author's
 * arithmetic instead of checking it.
 */
const WEEK_BUCKET_FIXTURE: { rows: { ts: number; bucket: number; label: string }[] } = JSON.parse(
  readFileSync(join(WEB, "tests", "fixtures", "week-buckets.json"), "utf8"),
);

/** Build a week table the same way the Python encoder does: little-endian, no padding. */
function makeWeek(nLots: number, cellsPerLot: Uint8Array[], { rosterId = 42, builtTs = 1788675094 } = {}): ArrayBuffer {
  const N_BUCKETS = 336;
  const buf = new ArrayBuffer(HEADER_SIZE + nLots * N_BUCKETS * 2);
  const dv = new DataView(buf);
  new Uint8Array(buf).set(new TextEncoder().encode("PCW1"), 0);
  dv.setUint8(4, 1);
  dv.setUint32(5, builtTs, true);
  dv.setUint16(9, nLots, true);
  dv.setUint16(11, N_BUCKETS, true);
  dv.setUint8(13, 30);
  dv.setUint32(14, rosterId, true);
  const body = new Uint8Array(buf, HEADER_SIZE);
  cellsPerLot.forEach((row, lot) => body.set(row, lot * N_BUCKETS * 2));
  return buf;
}

/** One lot's full row of `(percent, support)` pairs, every bucket set to the same cell. */
function uniformRow(percent: number, support: number): Uint8Array {
  const row = new Uint8Array(336 * 2);
  for (let b = 0; b < 336; b++) {
    row[b * 2] = percent;
    row[b * 2 + 1] = support;
  }
  return row;
}

describe("weekBucket", () => {
  it("buckets a timestamp the way the Python side does", () => {
    // BUCKET 0 IS THURSDAY 00:00 TAIPEI, NOT MONDAY. `week_bucket` anchors on
    // the Unix epoch and does no calendar arithmetic, and 1970-01-01 was a
    // Thursday. Every value below comes from `web/tests/fixtures/week-buckets.json`,
    // generated by `scripts/build-seam-fixture.py` calling the real Python
    // `forecast.week_bucket` -- not from arithmetic restated here.
    expect(WEEK_BUCKET_FIXTURE.rows.length).toBeGreaterThan(50);
    for (const { ts, bucket, label } of WEEK_BUCKET_FIXTURE.rows) {
      expect(weekBucket(ts), `${label} (ts=${ts})`).toBe(bucket);
    }
  });

  it("stays in range for every fixture row, including the negative-timestamp ones", () => {
    for (const { ts } of WEEK_BUCKET_FIXTURE.rows) {
      const b = weekBucket(ts);
      expect(b).toBeGreaterThanOrEqual(0);
      expect(b).toBeLessThan(336);
    }
  });
});

describe("parseWeek", () => {
  it("reads the header little-endian, matching the Python encoder", () => {
    const buf = makeWeek(2, [uniformRow(50, 6), uniformRow(WEEK_UNKNOWN, 0)], { rosterId: 42, builtTs: 1788675094 });
    const table = parseWeek(buf);
    expect(table.nLots).toBe(2);
    expect(table.rosterId).toBe(42);
    expect(table.builtTs).toBe(1788675094);
    expect(table.cells.length).toBe(2 * 336 * 2);
  });

  it("reads roster_id as unsigned even past the int32 boundary", () => {
    // Bitwise ops in JS return signed 32-bit results; getUint32 must not.
    const buf = makeWeek(1, [uniformRow(50, 1)], { rosterId: 0xffffffff });
    expect(parseWeek(buf).rosterId).toBe(0xffffffff);
  });

  it("rejects a file whose magic is wrong", () => {
    const buf = makeWeek(1, [uniformRow(50, 1)]);
    new Uint8Array(buf).set(new TextEncoder().encode("XXXX"), 0);
    expect(() => parseWeek(buf)).toThrow();
  });

  it("rejects a file shorter than the header", () => {
    expect(() => parseWeek(new ArrayBuffer(HEADER_SIZE - 1))).toThrow();
  });

  it("rejects a schema version this client does not read", () => {
    const buf = makeWeek(1, [uniformRow(50, 1)]);
    new DataView(buf).setUint8(4, 2);
    expect(() => parseWeek(buf)).toThrow();
  });

  it("rejects a header declaring a bucket count other than 336", () => {
    const buf = makeWeek(1, [uniformRow(50, 1)]);
    new DataView(buf).setUint16(11, 672, true);
    expect(() => parseWeek(buf)).toThrow();
  });

  it("rejects a header declaring a bucket width other than 30 min", () => {
    const buf = makeWeek(1, [uniformRow(50, 1)]);
    new DataView(buf).setUint8(13, 15);
    expect(() => parseWeek(buf)).toThrow();
  });

  it("rejects a body whose length disagrees with the header", () => {
    const buf = makeWeek(2, [uniformRow(50, 1), uniformRow(50, 1)]).slice(0, HEADER_SIZE + 336 * 2 + 5);
    expect(() => parseWeek(buf)).toThrow();
  });
});

describe("probabilityAt", () => {
  it("reports a real zero as a probability and an unknown as null", () => {
    // 255 is the unknown sentinel; 0 is a lot that is reliably full at this hour.
    const buf = makeWeek(2, [uniformRow(0, 6), uniformRow(WEEK_UNKNOWN, 0)]);
    const table = parseWeek(buf);
    const ts = 1789315200; // an arbitrary real timestamp
    expect(probabilityAt(table, 0, ts).p).toBe(0);
    expect(probabilityAt(table, 1, ts).p).toBeNull();
  });

  it("carries the support count alongside the probability", () => {
    const buf = makeWeek(1, [uniformRow(75, 12)]);
    const table = parseWeek(buf);
    const { p, support } = probabilityAt(table, 0, 1789315200);
    expect(p).toBeCloseTo(0.75, 5);
    expect(support).toBe(12);
  });

  it("is row-major: row i is lot i", () => {
    const buf = makeWeek(2, [uniformRow(10, 1), uniformRow(90, 1)]);
    const table = parseWeek(buf);
    expect(probabilityAt(table, 0, 1789315200).p).toBeCloseTo(0.1, 5);
    expect(probabilityAt(table, 1, 1789315200).p).toBeCloseTo(0.9, 5);
  });

  it("indexes by the actual time-of-week bucket, not just any cell", () => {
    // Pulled from the same fixture `weekBucket` is checked against above,
    // rather than hand-typing the bucket number a second time here.
    const { ts: mondayMidnight, bucket } = WEEK_BUCKET_FIXTURE.rows.find((r) => r.label === "Mon 00:00 Taipei")!;
    const row = uniformRow(0, 0);
    // Give that bucket a distinct, recognisable cell.
    row[bucket * 2] = 42;
    row[bucket * 2 + 1] = 7;
    const table = parseWeek(makeWeek(1, [row]));
    expect(weekBucket(mondayMidnight)).toBe(bucket);
    expect(probabilityAt(table, 0, mondayMidnight)).toEqual({ p: 0.42, support: 7 });
    // A different bucket on the same row reads its own (zeroed) cell.
    expect(probabilityAt(table, 0, mondayMidnight - 3600).p).toBe(0);
  });

  it("throws for a lot index outside the table", () => {
    const table = parseWeek(makeWeek(1, [uniformRow(50, 1)]));
    expect(() => probabilityAt(table, 1, 1789315200)).toThrow(RangeError);
    expect(() => probabilityAt(table, -1, 1789315200)).toThrow(RangeError);
  });

  it("throws for a non-finite ts instead of laundering it into a NaN probability", () => {
    // A malformed or empty <select> value is exactly how NaN would arrive
    // here from the (not yet built) time picker -- see the docstring above
    // `probabilityAt`. Without this guard, weekBucket(NaN) is NaN, the cell
    // lookup reads cells[NaN] (undefined, not a thrown error), and p comes
    // back NaN: a number, passing any "is this real" check a caller writes.
    const table = parseWeek(makeWeek(1, [uniformRow(50, 1)]));
    expect(() => probabilityAt(table, 0, NaN)).toThrow(RangeError);
    expect(() => probabilityAt(table, 0, Infinity)).toThrow(RangeError);
    expect(() => probabilityAt(table, 0, -Infinity)).toThrow(RangeError);
  });
});

describe("blend", () => {
  it("weights the reading by the blend's own half-life", () => {
    // weight = 0.5 ** (minutes / 30): at the half-life the two contribute equally.
    expect(blend(5, 0.2, 30)).toBeCloseTo(0.6, 5);
    expect(blend(0, 0.2, 0)).toBe(0); // a full lot now is a full lot now
  });

  it("halves the reading's weight every BLEND_HALF_LIFE_MIN minutes", () => {
    expect(BLEND_HALF_LIFE_MIN).toBe(30);
    // near = 1 (observed free), so p is exactly the weight at any climatology.
    expect(blend(3, 0.4, 0)).toBeCloseTo(1.0, 10);
    expect(blend(3, 0.4, 30)).toBeCloseTo(0.5 * 1 + 0.5 * 0.4, 10);
    expect(blend(3, 0.4, 60)).toBeCloseTo(0.25 * 1 + 0.75 * 0.4, 10);
  });

  it("falls back to pure climatology when there is no live reading at all", () => {
    // null means "no reading", not "empty" -- distinct from observedFree=0,
    // which is itself evidence (a lot seen with zero free spaces).
    expect(blend(null, 0.37, 5)).toBe(0.37);
    expect(blend(null, 0.37, 120)).toBe(0.37);
  });

  it("treats any observedFree >= 1 as full confidence in availability", () => {
    expect(blend(1, 0, 0)).toBe(1);
    expect(blend(99, 0, 0)).toBe(1);
  });

  it("clamps a negative minutesFromReading instead of returning a probability above 1", () => {
    // A user-driven time picker can legitimately ask about a moment before
    // the reading it is blending against, unlike the server, which only ever
    // calls this formula with a positive step from grid.horizons(). Left
    // unclamped, weight = 0.5 ** (-60/30) = 4 and blend(5, 0.2, -60) would
    // return 3.4 -- a "probability" above 1. Clamping to a 0-minute horizon
    // instead caps confidence at exactly what the reading itself supports.
    expect(blend(5, 0.2, -60)).toBe(blend(5, 0.2, 0));
    expect(blend(5, 0.2, -60)).toBe(1);
    expect(blend(0, 0.9, -120)).toBe(blend(0, 0.9, 0));
  });
});
